In [1]:
import pandas as pd
import os

In [2]:
# pwd is present working directory
# cwd is current working directory
pwd = os.getcwd()

In [10]:
dataset = pd.read_excel(pwd + '\\WIP.xlsx')

In [5]:
dataset

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website
0,Argentina,ARG,2022-03-29,9.650467e+08,4.090719e+08,3.692445e+08,0.0,547230.0,21161.0,897.0,8096.0,12000.0,"CanSino, Moderna, Oxford/AstraZeneca, Pfizer/B...",Ministry of Health,https://covidstats.com.ar/
1,Aruba,ABW,2022-03-29,1.692310e+06,8.788400e+05,8.134700e+05,1000.0,770.0,15787.0,8199.0,7589.0,7180.0,Pfizer/BioNTech,Government of Aruba,https://www.government.aw
2,Australia,AUS,2022-03-29,5.624291e+08,2.220237e+08,2.120043e+08,635980.0,656880.0,2181.0,861.0,8221.0,25470.0,"Moderna, Oxford/AstraZeneca, Pfizer/BioNTech",Government of Australia via CovidBaseAU,https://covidbaseau.com/
3,Azerbaijan,AZE,2022-03-29,1.342503e+08,5.322427e+07,4.821276e+07,189570.0,80640.0,13132.0,5206.0,4716.0,7890.0,"Oxford/AstraZeneca, Pfizer/BioNTech, Sinovac, ...",Government of Azerbaijan,https://koronavirusinfo.az
4,Bangladesh,BGD,2022-03-29,2.436427e+09,1.275441e+09,1.077127e+09,51837370.0,24119250.0,1465.0,7669.0,6477.0,145030.0,"Johnson&Johnson, Moderna, Oxford/AstraZeneca, ...",Directorate General of Health Services,http://103.247.238.92/webportal/pages/covid19-...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86507,Norway,NOR,2020-12-05,0.000000e+00,0.000000e+00,NaN,0.0,0.0,0.0,0.0,NaN,0.0,"Moderna, Pfizer/BioNTech",Norwegian Institute of Public Health,https://github.com/folkehelseinstituttet/surve...
86508,Latvia,LVA,2020-12-04,1.000000e+01,1.000000e+01,NaN,NaN,NaN,0.0,0.0,NaN,NaN,"Johnson&Johnson, Moderna, Novavax, Pfizer/BioN...",National Health Service,https://data.gov.lv/dati/eng/dataset/covid19-v...
86509,Norway,NOR,2020-12-04,0.000000e+00,0.000000e+00,NaN,0.0,0.0,0.0,0.0,NaN,0.0,"Moderna, Pfizer/BioNTech",Norwegian Institute of Public Health,https://github.com/folkehelseinstituttet/surve...
86510,Norway,NOR,2020-12-03,0.000000e+00,0.000000e+00,NaN,0.0,0.0,0.0,0.0,NaN,0.0,"Moderna, Pfizer/BioNTech",Norwegian Institute of Public Health,https://github.com/folkehelseinstituttet/surve...
86511,Norway,NOR,2020-12-02,0.000000e+00,0.000000e+00,NaN,NaN,NaN,0.0,0.0,NaN,NaN,"Moderna, Pfizer/BioNTech",Norwegian Institute of Public Health,https://github.com/folkehelseinstituttet/surve...

Pertanyaan-pertanyaan:

1. Bagaimana perkembangan vaksinasi COVID-19 di seluruh dunia berdasarkan dataset dari Gabriel Preda?
2. Apa saja negara-negara dengan tingkat vaksinasi tertinggi dan terendah dalam dataset COVID-19 World Vaccination Progress?
3. Apakah ada pola khusus dalam penyebaran vaksinasi di berbagai benua, seperti Eropa, Asia, Amerika, dan Afrika?
4. Bagaimana perbandingan penggunaan jenis vaksin yang berbeda di berbagai negara? Apakah ada perbedaan dalam efektivitas vaksin yang digunakan?
5. Dapatkah kita mengidentifikasi negara-negara yang berhasil mengendalikan penyebaran COVID-19 melalui kampanye vaksinasi yang efektif?
6. Bagaimana tren vaksinasi seiring berjalannya waktu? Apakah terdapat periode di mana vaksinasi meningkat atau menurun secara signifikan?

# Pertanyaan 1, 2, 3, 5

In [6]:
dataset.columns

Index(['country', 'iso_code', 'date', 'total_vaccinations',
       'people_vaccinated', 'people_fully_vaccinated',
       'daily_vaccinations_raw', 'daily_vaccinations',
       'total_vaccinations_per_hundred', 'people_vaccinated_per_hundred',
       'people_fully_vaccinated_per_hundred', 'daily_vaccinations_per_million',
       'vaccines', 'source_name', 'source_website'],
      dtype='object')

In [11]:
q1 = dataset.copy()
q1.drop(['daily_vaccinations_raw', 'daily_vaccinations', 'total_vaccinations_per_hundred', 
         'people_vaccinated_per_hundred',
         'people_fully_vaccinated_per_hundred', 'daily_vaccinations_per_million',
         'source_name', 'source_website'], axis=1, inplace=True)

In [12]:
filtered_q1 = q1.dropna(subset=['people_vaccinated', 'people_fully_vaccinated'])
sorted_q1 = filtered_q1.sort_values(by=['date'], ascending=False)
latest_q1 = sorted_q1.groupby('country').apply(lambda x: x[x['date']==x['date'].max()])
latest_q1.reset_index(drop=True, inplace=True)
latest_q1

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,vaccines
0,Afghanistan,AFG,2022-03-22,57510150.0,50828240.0,44201270.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi..."
1,Albania,ALB,2022-03-24,27542440.0,12789020.0,12151990.0,"Oxford/AstraZeneca, Pfizer/BioNTech, Sinovac, ..."
2,Algeria,DZA,2022-03-09,137048950.0,74619320.0,61107120.0,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac..."
3,Andorra,AND,2022-03-13,1519970.0,578170.0,533670.0,"Moderna, Oxford/AstraZeneca, Pfizer/BioNTech"
4,Angola,AGO,2022-03-25,175354110.0,112350590.0,59937920.0,Oxford/AstraZeneca
...,...,...,...,...,...,...,...
218,Wales,OWID_WLS,2022-03-28,69274370.0,25286640.0,23993410.0,"Moderna, Oxford/AstraZeneca, Pfizer/BioNTech"
219,Wallis and Futuna,WLF,2022-03-21,129400.0,64830.0,64570.0,Moderna
220,Yemen,YEM,2022-03-16,8075020.0,6435010.0,4047810.0,"Johnson&Johnson, Oxford/AstraZeneca, Sinovac"
221,Zambia,ZMB,2022-02-27,28220090.0,24871490.0,18626140.0,"Johnson&Johnson, Oxford/AstraZeneca, Sinopharm..."
222,Zimbabwe,ZWE,2022-03-29,90397290.0,50531140.0,35102560.0,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac..."

In [13]:
continents = pd.read_csv(pwd + '\\continents2.csv')
continents

,name,alpha-2,alpha-3,country-code,iso_3166-2,region,sub-region,intermediate-region,region-code,sub-region-code,intermediate-region-code
0,Afghanistan,AF,AFG,4,ISO 3166-2:AF,Asia,Southern Asia,NaN,142.0,34.0,NaN
1,Ã…land Islands,AX,ALA,248,ISO 3166-2:AX,Europe,Northern Europe,NaN,150.0,154.0,NaN
2,Albania,AL,ALB,8,ISO 3166-2:AL,Europe,Southern Europe,NaN,150.0,39.0,NaN
3,Algeria,DZ,DZA,12,ISO 3166-2:DZ,Africa,Northern Africa,NaN,2.0,15.0,NaN
4,American Samoa,AS,ASM,16,ISO 3166-2:AS,Oceania,Polynesia,NaN,9.0,61.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
244,Wallis and Futuna,WF,WLF,876,ISO 3166-2:WF,Oceania,Polynesia,NaN,9.0,61.0,NaN
245,Western Sahara,EH,ESH,732,ISO 3166-2:EH,Africa,Northern Africa,NaN,2.0,15.0,NaN
246,Yemen,YE,YEM,887,ISO 3166-2:YE,Asia,Western Asia,NaN,142.0,145.0,NaN
247,Zambia,ZM,ZMB,894,ISO 3166-2:ZM,Africa,Sub-Saharan Africa,Eastern Africa,2.0,202.0,14.0
248,Zimbabwe,ZW,ZWE,716,ISO 3166-2:ZW,Africa,Sub-Saharan Africa,Eastern Africa,2.0,202.0,14.0

In [14]:
merged_q1 = pd.merge(left=latest_q1, right = continents, left_on = 'iso_code', right_on='alpha-3', how='left' )

In [15]:
merged_q1

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,vaccines,name,alpha-2,alpha-3,country-code,iso_3166-2,region,sub-region,intermediate-region,region-code,sub-region-code,intermediate-region-code
0,Afghanistan,AFG,2022-03-22,57510150.0,50828240.0,44201270.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",Afghanistan,AF,AFG,4.0,ISO 3166-2:AF,Asia,Southern Asia,NaN,142.0,34.0,NaN
1,Albania,ALB,2022-03-24,27542440.0,12789020.0,12151990.0,"Oxford/AstraZeneca, Pfizer/BioNTech, Sinovac, ...",Albania,AL,ALB,8.0,ISO 3166-2:AL,Europe,Southern Europe,NaN,150.0,39.0,NaN
2,Algeria,DZA,2022-03-09,137048950.0,74619320.0,61107120.0,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",Algeria,DZ,DZA,12.0,ISO 3166-2:DZ,Africa,Northern Africa,NaN,2.0,15.0,NaN
3,Andorra,AND,2022-03-13,1519970.0,578170.0,533670.0,"Moderna, Oxford/AstraZeneca, Pfizer/BioNTech",Andorra,AD,AND,20.0,ISO 3166-2:AD,Europe,Southern Europe,NaN,150.0,39.0,NaN
4,Angola,AGO,2022-03-25,175354110.0,112350590.0,59937920.0,Oxford/AstraZeneca,Angola,AO,AGO,24.0,ISO 3166-2:AO,Africa,Sub-Saharan Africa,Middle Africa,2.0,202.0,17.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
218,Wales,OWID_WLS,2022-03-28,69274370.0,25286640.0,23993410.0,"Moderna, Oxford/AstraZeneca, Pfizer/BioNTech",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
219,Wallis and Futuna,WLF,2022-03-21,129400.0,64830.0,64570.0,Moderna,Wallis and Futuna,WF,WLF,876.0,ISO 3166-2:WF,Oceania,Polynesia,NaN,9.0,61.0,NaN
220,Yemen,YEM,2022-03-16,8075020.0,6435010.0,4047810.0,"Johnson&Johnson, Oxford/AstraZeneca, Sinovac",Yemen,YE,YEM,887.0,ISO 3166-2:YE,Asia,Western Asia,NaN,142.0,145.0,NaN
221,Zambia,ZMB,2022-02-27,28220090.0,24871490.0,18626140.0,"Johnson&Johnson, Oxford/AstraZeneca, Sinopharm...",Zambia,ZM,ZMB,894.0,ISO 3166-2:ZM,Africa,Sub-Saharan Africa,Eastern Africa,2.0,202.0,14.0
222,Zimbabwe,ZWE,2022-03-29,90397290.0,50531140.0,35102560.0,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",Zimbabwe,ZW,ZWE,716.0,ISO 3166-2:ZW,Africa,Sub-Saharan Africa,Eastern Africa,2.0,202.0,14.0

In [16]:
merged_q1.columns
merged_q1.drop(['name', 'alpha-2', 'alpha-3', 'country-code', 'iso_3166-2', 
                'intermediate-region', 'region-code', 'sub-region-code','intermediate-region-code']
               , axis=1, inplace=True)

In [17]:
merged_q1

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,vaccines,region,sub-region
0,Afghanistan,AFG,2022-03-22,57510150.0,50828240.0,44201270.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",Asia,Southern Asia
1,Albania,ALB,2022-03-24,27542440.0,12789020.0,12151990.0,"Oxford/AstraZeneca, Pfizer/BioNTech, Sinovac, ...",Europe,Southern Europe
2,Algeria,DZA,2022-03-09,137048950.0,74619320.0,61107120.0,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",Africa,Northern Africa
3,Andorra,AND,2022-03-13,1519970.0,578170.0,533670.0,"Moderna, Oxford/AstraZeneca, Pfizer/BioNTech",Europe,Southern Europe
4,Angola,AGO,2022-03-25,175354110.0,112350590.0,59937920.0,Oxford/AstraZeneca,Africa,Sub-Saharan Africa
...,...,...,...,...,...,...,...,...,...
218,Wales,OWID_WLS,2022-03-28,69274370.0,25286640.0,23993410.0,"Moderna, Oxford/AstraZeneca, Pfizer/BioNTech",NaN,NaN
219,Wallis and Futuna,WLF,2022-03-21,129400.0,64830.0,64570.0,Moderna,Oceania,Polynesia
220,Yemen,YEM,2022-03-16,8075020.0,6435010.0,4047810.0,"Johnson&Johnson, Oxford/AstraZeneca, Sinovac",Asia,Western Asia
221,Zambia,ZMB,2022-02-27,28220090.0,24871490.0,18626140.0,"Johnson&Johnson, Oxford/AstraZeneca, Sinopharm...",Africa,Sub-Saharan Africa
222,Zimbabwe,ZWE,2022-03-29,90397290.0,50531140.0,35102560.0,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",Africa,Sub-Saharan Africa

In [90]:
merged_q1.columns

Index(['country', 'iso_code', 'date', 'total_vaccinations',
       'people_vaccinated', 'people_fully_vaccinated', 'vaccines', 'region',
       'sub-region'],
      dtype='object')

In [18]:
merged_q1.insert(2,'region',merged_q1.pop('region'))
merged_q1.insert(3,'sub-region',merged_q1.pop('sub-region'))

In [19]:
merged_q1

,country,iso_code,region,sub-region,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,vaccines
0,Afghanistan,AFG,Asia,Southern Asia,2022-03-22,57510150.0,50828240.0,44201270.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi..."
1,Albania,ALB,Europe,Southern Europe,2022-03-24,27542440.0,12789020.0,12151990.0,"Oxford/AstraZeneca, Pfizer/BioNTech, Sinovac, ..."
2,Algeria,DZA,Africa,Northern Africa,2022-03-09,137048950.0,74619320.0,61107120.0,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac..."
3,Andorra,AND,Europe,Southern Europe,2022-03-13,1519970.0,578170.0,533670.0,"Moderna, Oxford/AstraZeneca, Pfizer/BioNTech"
4,Angola,AGO,Africa,Sub-Saharan Africa,2022-03-25,175354110.0,112350590.0,59937920.0,Oxford/AstraZeneca
...,...,...,...,...,...,...,...,...,...
218,Wales,OWID_WLS,NaN,NaN,2022-03-28,69274370.0,25286640.0,23993410.0,"Moderna, Oxford/AstraZeneca, Pfizer/BioNTech"
219,Wallis and Futuna,WLF,Oceania,Polynesia,2022-03-21,129400.0,64830.0,64570.0,Moderna
220,Yemen,YEM,Asia,Western Asia,2022-03-16,8075020.0,6435010.0,4047810.0,"Johnson&Johnson, Oxford/AstraZeneca, Sinovac"
221,Zambia,ZMB,Africa,Sub-Saharan Africa,2022-02-27,28220090.0,24871490.0,18626140.0,"Johnson&Johnson, Oxford/AstraZeneca, Sinopharm..."
222,Zimbabwe,ZWE,Africa,Sub-Saharan Africa,2022-03-29,90397290.0,50531140.0,35102560.0,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac..."

In [21]:
merged_q1.to_excel(pwd + '\\modfied_country_vaccinations.xlsx',
                   sheet_name='Latest Vaccination', 
                   index=False)

Pertanyaan-pertanyaan:

1. Bagaimana perkembangan vaksinasi COVID-19 di seluruh dunia berdasarkan dataset dari Gabriel Preda?
2. Apa saja negara-negara dengan tingkat vaksinasi tertinggi dan terendah dalam dataset COVID-19 World Vaccination Progress?
3. Apakah ada pola khusus dalam penyebaran vaksinasi di berbagai benua, seperti Eropa, Asia, Amerika, dan Afrika?
4. Bagaimana perbandingan penggunaan jenis vaksin yang berbeda di berbagai negara? Apakah ada perbedaan dalam efektivitas vaksin yang digunakan?
5. Dapatkah kita mengidentifikasi negara-negara yang berhasil mengendalikan penyebaran COVID-19 melalui kampanye vaksinasi yang efektif?
6. Bagaimana tren vaksinasi seiring berjalannya waktu? Apakah terdapat periode di mana vaksinasi meningkat atau menurun secara signifikan?

### Menambahkan nama negara ke dalam data 'List Vaccines'

In [22]:
list_countries_df = pd.read_excel(pwd + '\\modfied_country_vaccinations.xlsx',
                                  sheet_name='Latest Vaccination')

In [ ]:
list_vaccines_df = pd.DataFrame(columns=['vaccine','country','number_of_countries'])
vaccines_list = list_countries_df['vaccines'].str.split(', ')
unique_vaccines = list(set(vaccine for sublist in vaccines_list for vaccine in sublist))

for vaccine in unique_vaccines:
    countries = list(list_countries_df[list_countries_df['vaccines'].str.contains(vaccine)]['country'])
    num_countries = list_countries_df[list_countries_df['vaccines'].str.contains(vaccine)]['country'].nunique()
    
    for country in countries:
        list_vaccines_df = list_vaccines_df.append({'vaccine':vaccine, 'country':country, 'number_of_countries':num_countries},
                                 ignore_index=True)

In [26]:
list_vaccines_df.sort_values(by='vaccine', ascending=True, inplace=True)
list_vaccines_df.reset_index(drop=True, inplace=True)

list_vaccines_df

             vaccine       country number_of_countries
0             Abdala     Venezuela                   4
1             Abdala     Nicaragua                   4
2             Abdala       Vietnam                   4
3             Abdala          Cuba                   4
4    COVIran Barekat          Iran                   1
..               ...           ...                 ...
773        Sputnik V          Iraq                  58
774         Turkovac        Turkey                   1
775           ZF2001    Uzbekistan                   3
776           ZF2001         China                   3
777           ZF2001  Turkmenistan                   3

[778 rows x 3 columns]

In [27]:
with pd.ExcelWriter(pwd + '\\modfied_country_vaccinations.xlsx', engine='openpyxl', mode='a') as writer:
    list_vaccines_df.to_excel(writer, sheet_name='List Vaccines New', index=False)